### ISSUE TITLE
Updatelink 39mil passwords

### ISSUE THREAD

**Issue by Gatorfish** [hacxx-underground/Files#10]
Wanna send me out updated to pass list?

**Comment by hack-ito** [comment]
If is (39mil) Aptoide.com Database Leaked April 2020, the password is: #@!#(@)!%*^&&!!!#$%^##

**Comment by Gatorfish** [comment]
https://github.com/hacxx-underground/Files/blob/main/(39mil)%20Aptoide.com%20Database%20Leaked%20April%202020%20-%20Free%20Download

that link is to your posting on git for the 39mil. 

I am looking for the canva leak which you appear to have, but also the "download this" leak.

**Comment by Gatorfish** [comment]
Yes, but I couldn't get any of the links or mirrors to work....

**Comment by hacxx-underground** [comment]
This file has been archived after a prolonged period of inactivity and
i dont have the file anymore as the archive got corrupted.

**Comment by hacxx-underground** [comment]
Here a link for (39mil) Aptoide.com Database Leaked April 2020

https://yodbox.com/apk65g8ywsac/ap-20m-part1.7z.html

**Comment by hacxx-underground** [comment]
Here a link for Canva.com database leaked 24th May 2019

https://fastclick.to/27g8ww8rbblu
