### ISSUE TITLE
Links don't work

### ISSUE THREAD

**Issue by gafarchik** [hacxx-underground/Files#11]
Canva.com database leaked 24th May 2019 links don't work. Can you reload file to normal service? For example mega or something same

**Comment by hacxx-underground** [comment]
08/01/2023 - Re-uploaded...
https://uploadgig.com/file/download/16e8aEe687fd1ed7/Canva.com20database20leaked2024th20May202019.7z

**Comment by gafarchik** [comment]
I can't unzip it, error: file is damaged 

p7zip log
` 
ERRORS:
Is not archive
`

**Comment by hacxx-underground** [comment]
You didn't download the file completly. The file is 6.60 GB.

The reason why it is 7z is because the database is text and 7z is the best compression method for this type of files.

**Comment by Etix7** [comment]
Hi @hacxx-underground , Can you upload the Myfitnesspal database (FULL with hashes please) ?

**Comment by hacxx-underground** [comment]
View here:
https://link-target.net/68451/myfitnesspal-full-dump

**Comment by Etix7** [comment]
Do you have a link with nitroflare please?

**Comment by hacxx-underground** [comment]
No

**Comment by llmloverllm** [comment]
> View here: https://link-target.net/68451/myfitnesspal-full-dump

hi, can you reupload please? link doesn't work anymore
