### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by TheUnsocialEngineer** [hacxx-underground/Files#13]
adfly link is down :(

**Comment by hacxx-underground** [comment]
From which post?

**Comment by Fl0rri** [comment]
> adfly link is down :(

Dragon add my new discord p0lar#0452 I want to do a quick interview zombie really wants to talk to you. (If you are wondering none of the old members are involved anymore I sorted everything out so you don't have to worry about that.)

**Comment by lsdjunt** [comment]
> From which post?

scent bird data breach,  the links are burnt

**Comment by hacxx-underground** [comment]
Download from ddownload.
https://ddownload.com/d6flj6s6tcrl/Scentbird_Database_Leaked_June_2020.rar

**Comment by lsdjunt** [comment]
Goated maneuver🦾

**Comment by lsdjunt** [comment]
do you by any chance have the MGM data leak too?

**Comment by hacxx-underground** [comment]
Check here:
https://github.com/hacxx-underground/Files/blob/main/MGM%20Resorts%20Database%20Leaked%20July%202019%20-%20Free%20Download

**Comment by lsdjunt** [comment]
that link takes u to breached its like 8 tokens to get it

**Comment by lsdjunt** [comment]
i got it thx, add me on tele. frankiebales
