### ISSUE TITLE
Wattpad Full SQL Database Leaked June 2020 - Free Download

### ISSUE THREAD

**Issue by DennyResx** [hacxx-underground/Files#15]
Hi, the link on gigapeta has a 7z that it's incomplete. (http://gigapeta.com/dl/10444656a228145)

In fact the size is not 22.05GB and 7z cannot open the zip. I tried to put the EOA marker but no luck.

**Comment by DennyResx** [comment]
bro it costs 8 credits on that website lol

**Comment by hacxx-underground** [comment]
You have to unlock the thread which cost 8 credits ≅ 2$.
