### ISSUE TITLE
Canva data breach link does not work 

### ISSUE THREAD

**Issue by tigercoding56** [hacxx-underground/Files#16]
i wanted to train a neural network using some data from the canva data breach (patterns in how usernames are made ) but 1 of the links is to slow and times out every time   and the 2nd is blocked by tplink homesecurity (which i do not want to disable )

**Comment by hacxx-underground** [comment]
The idea when i start collecting databases was to build and teach an ai on how to give a email and password from the data.
I have delete the dbs, as i do not intent to build anymore.

Check this service that basically does what i was trying to build.
https://scatteredsecrets.com/

**Comment by tigercoding56** [comment]
> The idea when i start collecting databases was to build and teach an ai on how to give a email and password from the data. I have delete the dbs, as i do not intent to build anymore.
> 
> Check this service that basically does what i was trying to build. https://scatteredsecrets.com/

Ty
