### ISSUE TITLE
apollo's 7z seems error

### ISSUE THREAD

**Issue by alex-lx** [hacxx-underground/Files#17]
apollo's 7z seems error
https://www.emload.com/v2/file/ZUFFeHRUMEZEUWpYWkJSbzFDalphZz09/Apollo-Database-Leaked-23-July-2018.7z
39

when use `7z x apllo.7z`

```

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 760055509 bytes (725 MiB)

Extracting archive: apollo.7z
ERROR: apollo.7z
apollo.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Unexpected end of archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```

**Comment by alex-lx** [comment]
Still not work
```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1028955059 bytes (982 MiB)

Extracting archive: apollo-2018.7z
ERROR: apollo-2018.7z
apollo-2018.7z
Open ERROR: Can not open the file as [7z] archive


ERRORS:
Unexpected end of archive
    
Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
```

**Comment by hacxx-underground** [comment]
> Still not work
> 
> ```
> 7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
> p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Xeon(R) CPU E5-2682 v4 @ 2.50GHz (406F1),ASM,AES-NI)
> 
> Scanning the drive for archives:
> 1 file, 1028955059 bytes (982 MiB)
> 
> Extracting archive: apollo-2018.7z
> ERROR: apollo-2018.7z
> apollo-2018.7z
> Open ERROR: Can not open the file as [7z] archive
> 
> 
> ERRORS:
> Unexpected end of archive
>     
> Can't open as archive: 1
> Files: 0
> Size:       0
> Compressed: 0
> ```

Open with 7zip. also i don't have the file anymore.
