### ISSUE TITLE
.sql

### ISSUE THREAD

**Issue by Gazel1** [hacxx-underground/Files#18]
Sorry for the stupid question, but what is the most efficient way to open a .sql file?

**Comment by Gazel1** [comment]
I use w10

**Comment by Gazel1** [comment]
my OS is w10

**Comment by hacxx-underground** [comment]
>
> Sorry for the stupid question, but what is the most efficient way to open
> a .sql file?
>
Open with a text editor like EmEditor -
https://nitroflare.com/view/1EEEED1494A0D1F/EmEditor_Profissional_%2832-bit%29_16.0.2.rar

**Comment by hacxx-underground** [comment]
> my OS is w10
>
>
> Yes, works with Windows 10. Be sure to have or a lot of RAM or a lot of
disk space.
