### ISSUE TITLE
Fail to download the data through the link

### ISSUE THREAD

**Issue by Er1cCh4n** [hacxx-underground/Files#19]
fail to reach the data through the link：

Download: (Original)
1 - https://direct-link.net/68451/twitter-200m-data-breach
2 - https://link-target.net/68451/twitter-200m-data-breach1

**Comment by Leth4lity** [comment]
Anything that directs you towards "linkvertise.com" doesnt work l.

**Comment by hacxx-underground** [comment]
> fail to reach the data through the link：
> 
> Download: (Original) 1 - https://direct-link.net/68451/twitter-200m-data-breach 2 - https://link-target.net/68451/twitter-200m-data-breach1

Good luck finding a working link.

**Comment by hacxx-underground** [comment]
> Anything that directs you towards "linkvertise.com" doesn't work l.

Not all but some doesn't work.
