### ISSUE TITLE
About a leak lost in the takedown of breached…

### ISSUE THREAD

**Issue by averynormaltaco** [hacxx-underground/Files#22]
Do or anyone you know you still happen to have the [Teespring database that was leaked April 2020](https://github.com/hacxx-underground/Files/blob/main/Teespring%20database%20leaked%20April%202020%20-%20Free%20Download), I have been looking for it for some time and now someone else has joined me and we are willing to even pay if needed, many thanks.

**Comment by hacxx-underground** [comment]
No, i don't have the archive and i it will not be possible to find even if you pay.
