### ISSUE TITLE
File corrupt

### ISSUE THREAD

**Issue by ImJoke** [hacxx-underground/Files#23]
Corrupted file : Canva.com database leaked 24th May 2019

I cannot extract it, can you reupload it?

**Comment by hacxx-underground** [comment]
Download here

https://uploadgig.com/file/download/16e8aEe687fd1ed7/Canva.com20database20leaked2024th20May202019.7z

Corrupted file : Canva.com database leaked 24th May 2019
>
> I cannot extract it, can you reupload it?
>

**Comment by Shwepsssss** [comment]
Wattpad archive Corrupted from the only link that works which is:(
http://gigapeta.com/dl/10444656a228145

**Comment by hacxx-underground** [comment]
> Wattpad archive Corrupted from the only link that works which is:( http://gigapeta.com/dl/10444656a228145

I have Wattpad in combo format, will upload later when possible.
