### ISSUE TITLE
Can you please reupload Bigbasket leak

### ISSUE THREAD

**Issue by varun7952** [hacxx-underground/Files#24]
Please reupload bigbasket leak over megaupload or google drive please
[https://github.com/hacxx-underground/Files/issuesBigbasket.com Database Leaked November 2020](https://github.com/hacxx-underground/Files/blob/main/Bigbasket.com%20Database%20Leaked%20November%202020)

**Comment by hacxx-underground** [comment]
Use NitroFlare or Nitro.download links.

**Comment by varun7952** [comment]
Nitro is paid one brother.
![Screenshot 2023-05-06 at 19-20-36 NitroFlare - Upload Files](https://user-images.githubusercontent.com/12626827/236628333-28259b19-03fc-4854-b425-07ce0ba0e19b.png)

**Comment by hacxx-underground** [comment]
most likely i don't have the file anymore and you may need to buy premium to download for $12.50.

**Comment by hacxx-underground** [comment]
You can use **Hacxx Hash Cracker 4 Trial** to crack

Bigbasket.com Database Leaked November 2020
https://github.com/hacxx-underground/Files/blob/main/Bigbasket.com%20Database%20Leaked%20November%202020

The passwords: sha1 hashed password

**Comment by hacxx-underground** [comment]
[REPOST] Bigbasket.com database leaked November 2020

**DOWNLOAD:**
https://filerice.com/j49so1xfsssf/Bigbasket.com_database_leaked_November_2020.7z

**Comment by hacxx-underground** [comment]
Hacxx Hash Cracker 4 Trial - Decrypt MD5, SHA1, MySQL, NTLM, SHA256 and SHA512

- Decrypt MD5, SHA1, MySQL, NTLM, SHA256 and SHA512
- Identify MD5, SHA1, SHA256 and SHA512

**Download:**
https://filecrypt.cc/Container/AF6A4623FD.html
https://oxy.st/d/EbIg
https://nitroflare.com/view/5E756E252CE1CDB

**Comment by varun7952** [comment]
the filerice,nitro etc having limit of download file size and big basket is around 3 GB. If its possible for you to create Mega,drive or any other where i can download the file. Please :)

**Comment by hacxx-underground** [comment]
> the FileRice, Nitro etc having limit of download file size and big basket is around 3 GB. If its possible for you to create Mega, drive or any other where i can download the file. Please :)

Download from the link below:
https://www.linkbox.to/f-detail/ZnAzdGVnMDAwamRw0

**Comment by varun7952** [comment]
> Hacxx Hash Cracker 4 Trial - Decrypt MD5, SHA1, MySQL, NTLM, SHA256 and SHA512
> 
>     * Decrypt MD5, SHA1, MySQL, NTLM, SHA256 and SHA512
> 
>     * Identify MD5, SHA1, SHA256 and SHA512
> 
> 
> **Download:** https://filecrypt.cc/Container/AF6A4623FD.html https://oxy.st/d/EbIg https://nitroflare.com/view/5E756E252CE1CDB

Can you also upload this on somewhere better place. Nitro is not working for me.

**Comment by hacxx-underground** [comment]
> https://oxy.st/d/EbIg

Use the this link on a windows computer.

**Comment by varun7952** [comment]
i saved the BB leak on google drive of mine. If you ever need a copy please let me know. Btw its 3GB in zip and when i extract it its comes out 11 GB+ and its really hard to load that SQL on windows without MYSQL Server but anyway thanks alot for your help.

**Comment by hacxx-underground** [comment]
> i saved the BB leak on google drive of mine. If you ever need a copy please let me know. Btw its 3GB in zip and when i extract it its comes out 11 GB+ and its really hard to load that SQL on windows without MYSQL Server but anyway thanks alot for your help.

Open with a text editor like EmEditor -
https://nitroflare.com/view/1EEEED1494A0D1F/EmEditor_Profissional_%2832-bit%29_16.0.2.rar
