### ISSUE TITLE
Deezer breach, could you do me a favour?

### ISSUE THREAD

**Issue by alx080** [hacxx-underground/Files#25]
Hey, could you or somebody check for the data linked to the mail address "a-0ne@t-online.de" in the 30GB Deezer leak?
I need to know if it's just the email or what other data entries can be found.
Thanks!

**Comment by hacxx-underground** [comment]
Here the breaches for that email.

000webhost > Aternos > Deezer > iMesh > Twitter (200M) > ZAP-Hosting

**Comment by alx080** [comment]
Hey, thanks for the quick reply, can you check for name/address/gender etc. in the Deezer breach?

**Comment by hacxx-underground** [comment]
> Hey, thanks for the quick reply, can you check for name/address/gender etc. in the Deezer breach?

No, can't help you on that...

The database is available below
https://github.com/hacxx-underground/Files/blob/main/Deezer%20Database%20Leaked%20September%202019%20-%20Free%20Download
