### ISSUE TITLE
Do you have romwe database leak?

### ISSUE THREAD

**Issue by varun7952** [hacxx-underground/Files#27]
Hi again, Do you have romwe database leak? I have but i think its not complete because i can see emails in breaks but not in database. What i have is zip file around 160MB.

https://anonfiles.com/h674Idt2u4/rufxa3wthy_rar

**Comment by hacxx-underground** [comment]
> Hi again, Do you have romwe database leak? I have but i think its not complete because i can see emails in breaks but not in database. What i have is zip file around 160MB.
> 
> https://anonfiles.com/h674Idt2u4/rufxa3wthy_rar

No i don't have that database. Will re-upload your file and re-share.
Thanks

**Comment by hacxx-underground** [comment]
After reviewing the archive all text files are combos, separate by country in email:password.
Thanks.
