### ISSUE TITLE
MyFitnesPal link dead, could you help update it, thanks

### ISSUE THREAD

**Issue by md018** [hacxx-underground/Files#28]
https://github.com/hacxx-underground/Files/blob/main/MyFitnessPal%20Full%20Dump%20-%20Free%20Download

**Comment by hacxx-underground** [comment]
Check here...
https://link-target.net/68451/myfitnesspal-full-dump

or here...
https://ddownload.com/woz28r92embm/myfitnesspal_emailpass_50M.rar

**Comment by stellarzenithdreamerzephyr** [comment]
> https://ddownload.com/woz28r92embm/myfitnesspal_emailpass_50M.rar > not full dump
Combo - email:password format.

Refer here:
https://rumble.com/v2f1e6c-how-the-fbi-caught-hacker-pompompurin-seytonic.html

**Comment by kkurts** [comment]
does anyone have a full dump?
