### ISSUE TITLE
AJ

### ISSUE THREAD

**Issue by BarelyBacca** [hacxx-underground/Files#29]
Do you have access to the Animal Jam database still? or since link is no longer working you don't have access?

**Comment by hacxx-underground** [comment]
I no longer have that file. If the purpose is password solving then use Hacxx iLeaked Solver as a Service.

**Comment by BarelyBacca** [comment]
> I no longer have that file. If the purpose is password solving then use Hacxx iLeaked Solver as a Service.

hm heard ill look into this, do you have a discord I can add? or if you use anything for communication.

**Comment by stellarzenithdreamerzephyr** [comment]
> hm heard ill look into this, do you have a discord I can add? or if you use anything for communication.

View a simple usage of **Hacxx iLeaked Solver for android - HiLSAS 3-1.0**
https://rumble.com/v2pdxn6-hacxx-ileaked-solver-as-a-service-for-android-hilsas-3-1.0.apk.html

You get 90 lockups free using the code in the video.

**Comment by hacxx-underground** [comment]
> hm heard ill look into this, do you have a discord I can add? or if you use anything for communication.

Do you have tg? Send me your username.

**Comment by BarelyBacca** [comment]
> > hm heard ill look into this, do you have a discord I can add? or if you use anything for communication.
> 
> Do you have tg? Send me your username.

barelybacca is telegram

**Comment by hacxx-underground** [comment]
> barelybacca is telegram

Check your tg.
