### ISSUE TITLE
is the link dead?

### ISSUE THREAD

**Issue by bob-24** [hacxx-underground/Files#31]
is the torrent link dead for 400 GB + SOME UNIQUE LEAKED DATABASE COLLECTION? cant download the files. do you have the files?

**Comment by hacxx-underground** [comment]
> is the torrent link dead for 400 GB + SOME UNIQUE LEAKED DATABASE COLLECTION? cant download the files. do you have the files?

The magnet is working, i'm unable to download or test the files.
