### ISSUE TITLE
RaidForums Massive Database Collection Links Down

### ISSUE THREAD

**Issue by Unovamata** [hacxx-underground/Files#32]
Link shorteners are either: removing the key needed to decrypt the download link or redirecting to sites that do not work, connect, or won't host the files anymore.

**Comment by hacxx-underground** [comment]
> Link shorteners are either: removing the key needed to decrypt the download link or redirecting to sites that do not work, connect, or won't host the files anymore.

**removing the key needed to decrypt the download link**
- Yes, links for mega.nz are blocked from shorteners.

**redirecting to sites that do not work, connect, or won't host the files anymore**
- Yes, Breached.vc CDN links no longer works.

**Comment by Unovamata** [comment]
So I imagine this issue is solved as the files are not accessible anymore. So I'm going to close the issue, feel free to reopen it if needed.
