### ISSUE TITLE
Regarding Linkedin Company data

### ISSUE THREAD

**Issue by sparkler22** [hacxx-underground/Files#34]
Hi hacxx-underground,

I am looking for linkedin company data.It will be very helpful for me if you can able to provide a active link for that. Previous links are not working.

Thanks in advance

**Comment by hacxx-underground** [comment]
> I am looking for linkedin company data.It will be very helpful for me if you can able to provide a active link for that. Previous links are not working.

Use the search function
https://github.com/search?q=repo%3Ahacxx-underground%2FFiles%20linkedin&type=code
