### ISSUE TITLE
where to get complete dataset?

### ISSUE THREAD

**Issue by bob-24** [hacxx-underground/Files#35]
where to get complete 700M linkes for this dataset:

https://github.com/hacxx-underground/Files/blob/ce94c28a77d0d8f081185e989a39a96b6a955981/Sample%201%20Million%20LinkedIn%20data%20leaked%2022%20June%202021%20-%20Free%20Download#L6

?

**Comment by hacxx-underground** [comment]
Here:
https://github.com/hacxx-underground/Files/blob/ce94c28a77d0d8f081185e989a39a96b6a955981/Linkedin%20Scrapped%20Data%202021%20%5B200GB-1.4TB%5D%5B400M%5D#L6

**Comment by bob-24** [comment]
But this contains 400 Million entries. The other one says there are 700 Million. Is there a mistake somewhere?
