### ISSUE TITLE
problem with download

### ISSUE THREAD

**Issue by PijeWode** [hacxx-underground/Files#36]
Can u post a dehashed database link on free service cuz i cant even download it on nitroflare on free version

(https://nitroflare.com/view/541CA0BDA25CDB5/DEHASHED_-_DATABASE_-_COLLECTION_-_-_240%2B_-_DATABASES_-__-_EMAIL-PASS.7z)

**Comment by hacxx-underground** [comment]
> Can u post a dehashed database link on free service cuz i cant even download it on nitroflare on free version.

I no longer have that file.
