### ISSUE TITLE
Verifications.io 

### ISSUE THREAD

**Issue by kingkai88** [hacxx-underground/Files#37]
Is there a other mirror for this dataset?

**Comment by hacxx-underground** [comment]
**Here:**
https://github.com/hacxx-underground/Files/blob/main/Verifications.io%20Database%20Leaked%20February%202019%20-%20Free%20Download

https://github.com/hacxx-underground/Files/blob/main/%5BREPOST%5D%20Verifications.io%20Database%20

https://github.com/hacxx-underground/Files/blob/main/%5BREPOST%5D%20Verifications.io%20Database%20Leaked%20February%202019%20(250%20MB%20Parts)%20-%20Free%20Download
