### ISSUE TITLE
no seeders

### ISSUE THREAD

**Issue by bob-24** [hacxx-underground/Files#39]
there are no seeders for 400 GB + SOME UNIQUE LEAKED DATABASE COLLECTION . I am trying for more than a month. Is it the case that there is a new magnet?

I found another one: https://btdig.com/search?q=+Leaks+%E3%80%8CData+Breaches%E3%80%8D 

But that magnet also has no seeders. Is it possible to get some help? The list is in fact impressive.

**Comment by hacxx-underground** [comment]
Sorry can't help you out with the torrent. I tried leech the magnet, and when it reach 99% it didn't go any further.

**Comment by bob-24** [comment]
Does this mean you have 99% of the file?

**Comment by hacxx-underground** [comment]
> Does this mean you have 99% of the file?

No, i "torrent leech" with Filerice - https://filerice.com/free6824.html

The torrent was running until it hit 99% than stay that way for days.

**Comment by bob-24** [comment]
I see.
do you have access to: 
 Chinese DB Compilation 1.3 Billion 「Compiled In 2021」.7z20.31 GB
 and India Aadhaar?

**Comment by hacxx-underground** [comment]
No, i don't have the archive. Will check later and post if i find it.

**Comment by hacxx-underground** [comment]
> I see. do you have access to: Chinese DB Compilation 1.3 Billion 「Compiled In 2021」.7z20.31 GB and India Aadhaar?

Couldn't find the databases, sorry.
