### ISSUE TITLE
Download issue

### ISSUE THREAD

**Issue by under3565iuoio** [hacxx-underground/Files#40]
Sir, your given California email Leaked Database download is working, after downloading Exe file, I can't download the correct file

**Comment by hacxx-underground** [comment]
> Sir, your given California email Leaked Database download is working, after downloading file, I can't download the correct file

Give me the link to the thread that you are trying to download.

**Comment by under3565iuoio** [comment]
Sir this link https://github.com/hacxx-underground/Files/blob/main/University%20of%20California%20Database%20Leaked%20December%202020%20-%20Free%20Download

Screnshot link:https://prnt.sc/5wltu98gPwpY

**Comment by hacxx-underground** [comment]
I can get it, will post later.

**Comment by hacxx-underground** [comment]
> Thank you very much

Here
https://github.com/hacxx-underground/Files/blob/main/University%20of%20California%20Database%20Leaked%20December%202020

**Comment by hacxx-underground** [comment]
> Sir i can contact you telegram

Send me your tg username.

**Comment by under3565iuoio** [comment]
@Aontar750
