### ISSUE TITLE
breached.vc has been seized

### ISSUE THREAD

**Issue by baekaeni** [hacxx-underground/Files#41]
https://github.com/hacxx-underground/Files/blob/main/Weee%20Database%20leaked%20February%202023%20-%20Free%20Download

so, can you post it again?

**Comment by hacxx-underground** [comment]
Hi, yes will re-post...

**Comment by hacxx-underground** [comment]
> so, can you post it again?

Yes, here:
https://github.com/hacxx-underground/Files/blob/main/Weee!%20Database%20leaked%20February%202023%20-%20Full%20Download
