### ISSUE TITLE
Reupload Request

### ISSUE THREAD

**Issue by tr1fled** [hacxx-underground/Files#43]
Could you reupload the logs in https://github.com/hacxx-underground/Files/blob/main/Free%20Logs%20Gigapeta%20-%20Collected%20With%20Hacxx%20Logs%20Grabber%20Premium%20-%20January%202023 to gigapeta or oxy.st? Gigapeta took them down due to inactivity.

**Comment by hacxx-underground** [comment]
> Could you reupload the logs in https://github.com/hacxx-underground/Files/blob/main/Free%20Logs%20Gigapeta%20-%20Collected%20With%20Hacxx%20Logs%20Grabber%20Premium%20-%20January%202023 to gigapeta or oxy.st? Gigapeta took them down due to inactivity.

I don't have the archives anymore. I have delete the 404 ones, check post...
https://github.com/hacxx-underground/Files/blob/main/Free%20Logs%20Gigapeta%20-%20Collected%20With%20Hacxx%20Logs%20Grabber%20Premium%20-%20January%202023

**Comment by tr1fled** [comment]
Thank you!
