### ISSUE TITLE
I need the password for this rar.

### ISSUE THREAD

**Issue by hkalamsaida** [hacxx-underground/Files#46]
https://github.com/hacxx-underground/Files/blob/main/River%20City%20Media%20(RCM)%20Spam%20List%20Breached%20January%202017%20-%20Free%20Download

**Comment by hacxx-underground** [comment]
> https://github.com/hacxx-underground/Files/blob/main/River%20City%20Media%20(RCM)%20Spam%20List%20Breached%20January%202017%20-%20Free%20Download

I no longer have the archive.
