### ISSUE TITLE
Canva data

### ISSUE THREAD

**Issue by sandreask** [hacxx-underground/Files#47]
The canva links dont work for me. The download fails.

**Comment by hacxx-underground** [comment]
The download link is good.

**Download:**
https://uploadgig.com/file/download/16e8aEe687fd1ed7/Canva.com20database20leaked2024th20May202019.7z

I went more and create a tool with the databases, here.
https://github.com/hacxx-underground/Files/blob/main/Hacxx%20Databases%20V2023%20-%20Free%20Download
