### ISSUE TITLE
Discord.io Only pastebin not download

### ISSUE THREAD

**Issue by j4anm4** [hacxx-underground/Files#48]
Download:
https://direct-link.net/68451/discordio-database-leake
http://bc.vc/7giZFOq
http://adfoc.us/50323397419901
https://link.usalink.io/Discordio-Database
https://4cash.me/Discordio-Database
https://go.youshort.me/Discordio-Database
https://cuts-url.com/Discordio-Database

only a pastebin with the notice https://linkvertise.com/68451/discordio-database-leake/1

**Comment by hacxx-underground** [comment]
Yes, it's only invites.

**Comment by j4anm4** [comment]
but then why do you put Download that we are going to download a news item?

**Comment by hacxx-underground** [comment]
> but then why do you put Download that we are going to download a news item?

I will update the paste if the file start been shared online.

**Comment by hacxx-underground** [comment]
> I appreciate your work and congratulate you for everything you do, but it's just clickbait.

Yes
