### ISSUE TITLE
The data is from 2019-2021, the Iraqi Telecom company suffered a data breach that exposed 11+M accounts.  Download

### ISSUE THREAD

**Issue by Roronoa-Z0RO** [hacxx-underground/Files#49]
this download link which is breached.vc is not available please update

**Comment by Roronoa-Z0RO** [comment]
which is Zain Telecom Iraqi company

**Comment by hacxx-underground** [comment]
It was taken down by the FBI.

**Comment by hacxx-underground** [comment]
I don't have that one.

**Comment by hacxx-underground** [comment]
I was only able to find - **Asiacell Iragi Telecom Company** on BreachedForums.
