### ISSUE TITLE
How to buy

### ISSUE THREAD

**Issue by BurningRealSelf** [hacxx-underground/Files#5]
How to buy

**Comment by hacxx-underground** [comment]
What do you want to buy?

**Comment by BurningRealSelf** [comment]
Hacxx Fast Combo Grabber

**Comment by hacxx-underground** [comment]
40 EUR by paypal or bitcoin. It includes free updates.

**Comment by BurningRealSelf** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            Not $30?
        
    
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Hacxx ***@***.***>
            
        
      
      
        
         Date 
        
        
        11/8/2022 01:22
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [hacxx-underground/Files] How to buy (Issue #5)
        
      
    
  
  

40 EUR by paypal or bitcoin. It includes free updates.

**Comment by hacxx-underground** [comment]
Hi,


I have increase the price. Hacxx Fast Combo Grabber costs 40 EUR and i
include free updates and Config Grabber, Accounts Grabber and proxies
Grabber.

Paypal - ***@***.***
Bitcoin - 1CDh6w28hQx1VjtL7eZdrSZooZjmd9Pv4u

Thanks

**Comment by BurningRealSelf** [comment]
okay, do you have any other contact information? For example, TG, I'm going to pay by usdt

**Comment by BurningRealSelf** [comment]
***@***.***

**Comment by hacxx-underground** [comment]
Hi,

PayPal - ***@***.***
USDT (Tether (ERC-20)) - 0xBBDB290992a01B549Df523c3Ba6B99b21c152755

Thanks

**Comment by BurningRealSelf** [comment]
bro, I did not receive your addition

Hacxx Underground ***@***.***> 于 2022年11月9日周三 下午8:51写道：

> Hi, Send me your telegram username and i will add. About payment yes
> usdt is not a problem. Do you want the address to send the payment?
> Thanks
>

**Comment by BurningRealSelf** [comment]
my email ***@***.***

Hacxx Underground ***@***.***> 于 2022年11月9日周三 下午8:51写道：

> Hi, Send me your telegram username and i will add. About payment yes
> usdt is not a problem. Do you want the address to send the payment?
> Thanks
>

**Comment by hacxx-underground** [comment]
Can you give your username at telegram without the email. Github hides
the email.

**Comment by BurningRealSelf** [comment]
ye Telegram luchen

**Comment by hacxx-underground** [comment]
Added, check your telegram.

**Comment by hacxx-underground** [comment]
I will close the issue. Thanks.
