### ISSUE TITLE
No links for Deezer database download works

### ISSUE THREAD

**Issue by SkirmisLTU** [hacxx-underground/Files#50]
no links for Deezer database download works

**Comment by hacxx-underground** [comment]
> no links for Deezer database download works

Here:
https://rapidgator.net/file/527ac2229a1386fe2f4e3db608b7aa50/Deezer_Full_Database_Leaked_22_April_2019.7z.html
https://nitroflare.com/view/ECFF74F21FAF577/Deezer_Full_Database_Leaked_22_April_2019.7z
