### ISSUE TITLE
Verifications.io file corrupted

### ISSUE THREAD

**Issue by mayhem22** [hacxx-underground/Files#51]
The verifications.io database from rapidgator is corrupted. I downloaded it 2 times and same thing. Do you have other links ?

**Comment by hacxx-underground** [comment]
Download here (250 MB Parts):
https://github.com/hacxx-underground/Files/blob/main/%5BREPOST%5D%20Verifications.io%20Database%20Leaked%20February%202019%20(250%20MB%20Parts)%20-%20Free%20Download
