### ISSUE TITLE
"Deezer Database Leaked 22 April 2019 - 229M Customers - Free Download" I don't have the password

### ISSUE THREAD

**Issue by nepte** [hacxx-underground/Files#53]
Hi,

where do i get the password from "https://dl4free.com/?84f61q9kyjfx1ib7trdr" this link ?

**Comment by hacxx-underground** [comment]
Type the domain .cc

**Comment by nepte** [comment]
like "https://dl4free.cc/?84f61q9kyjfx1ib7trdr" ?
