### ISSUE TITLE
Weee Database leaked February 2023 - Free Download

### ISSUE THREAD

**Issue by dalvia62** [hacxx-underground/Files#55]
Link is not working for Weee database.

**Comment by hacxx-underground** [comment]
> Link is not working for Weee database.

Download:
https://filecrypt.cc/Container/C7E2DD9240.html
http://www.filefactory.com/file/1hqe00wxp3g
https://rapidgator.net/file/54ba309a1c4f05ff638807fd14e56753
https://nitroflare.com/view/9F0D723CA7417DB/Weee%21_Database_leaked_February_2023.7z
