### ISSUE TITLE
Wattpad 2020 Leak resubmission 

### ISSUE THREAD

**Issue by Spiderx11** [hacxx-underground/Files#63]
All of the below leaks haven’t worked, could you re upload?

also sidenote but props for all your work here this is amazing 

Download 1:
https://link-hub.net/68451/wattpad-database-leaked
http://adfoc.us/50323385856576
http://bc.vc/BxG7L1v
https://lnkload.com/2ABZm

Download 2:
https://filecrypt.cc/Container/1BA85274EA.html
https://nitroflare.com/view/37907B51B24B9BF/Wattpad_Database_Leaked_June_2020.7z
https://www.emload.com/v2/file/OEgySVh2d1c4TXJZc25QZjlLMzN0UT09/Wattpad-Database-Leaked-June-2020.7z

**Comment by hacxx-underground** [comment]
Both Nitroflare and emload has the file for download. The only problem is that is 22.05 GB, which is a bit large and you will have to purchase premium. I don't have the file anymore.
