### ISSUE TITLE
Verifications.io links don't work, please refresh them.

### ISSUE THREAD

**Issue by justinruck080** [hacxx-underground/Files#69]
Hello. I've had no way to contact you so this was my only way to do so. If possible please refresh the links for Verifications.io since they've been taken down or if there is any other way you can provide them to me, would be much appreciated.  Could I get your contact info, WhatsAPP?

**Comment by albotroz** [comment]
Yes please fix it.

**Comment by hacxx-underground** [comment]
> Hello. I've had no way to contact you so this was my only way to do so. If possible please refresh the links for Verifications.io since they've been taken down or if there is any other way you can provide them to me, would be much appreciated. Could I get your contact info, WhatsAPP?

Here:
https://github.com/hacxx-underground/Files/commit/d6ce9f1bc51879bbcee5ae37d913b990b20f958a

**Comment by hacxx-underground** [comment]
> Yes please fix it.

Here:
https://github.com/hacxx-underground/Files/commit/d6ce9f1bc51879bbcee5ae37d913b990b20f958a
