### ISSUE TITLE
Password to file

### ISSUE THREAD

**Issue by Splonkd** [hacxx-underground/Files#70]
https://github.com/hacxx-underground/Files/blob/main/CDEK.ru%20Database%20Leaked%2014%20of%20July%202022%20-%20Free%20Download

What is the password to the file above?

**Comment by sandercom** [comment]
pls give mee pass too

**Comment by sandercom** [comment]
> https://github.com/hacxx-underground/Files/blob/main/CDEK.ru%20Database%20Leaked%2014%20of%20July%202022%20-%20Free%20Download
> 
> What is the password to the file above?

**Comment by hacxx-underground** [comment]
> https://github.com/hacxx-underground/Files/blob/main/CDEK.ru%20Database%20Leaked%2014%20of%20July%202022%20-%20Free%20Download
> 
> What is the password to the file above?

Password: **breached**

**Comment by hacxx-underground** [comment]
> pls give mee pass too

Password: **breached**

**Comment by hacxx-underground** [comment]
> > https://github.com/hacxx-underground/Files/blob/main/CDEK.ru%20Database%20Leaked%2014%20of%20July%202022%20-%20Free%20Download
> > What is the password to the file above?
> 
> [sandercommander@mail.ru](mailto:sandercommander@mail.ru)

Password: **breached**
