### ISSUE TITLE
 Deezer file issue and download

### ISSUE THREAD

**Issue by under3565iuoio** [hacxx-underground/Files#72]
I downloaded the Deezer baaed email data from your GitHub, but when I unzip they don't work, and the same error comes up again and again,

Can you give me the correct download link, and I can unzip the files without any problem

Please will check the screenshot

![Screenshot_41](https://github.com/hacxx-underground/Files/assets/141177038/8c84eb42-f58f-4df1-9877-edff8d1c18e6)

**Comment by hacxx-underground** [comment]
Download here:
https://k2s.cc/file/ae782df82ef17/Deezer_Full_Database_Leaked_22_April_2019.7z
https://file.al/awjmsncnr9jv/Deezer_Full_Database_Leaked_22_April_2019.7z.html
