### ISSUE TITLE
Linkedin Scrapped Data 2021 [200GB-1.4TB][400M] The files has been removed. 

### ISSUE THREAD

**Issue by Endt4sk** [hacxx-underground/Files#77]
Linkedin Scrapped Data 2021 [200GB-1.4TB][400M] The files has been removed.

**Comment by hacxx-underground** [comment]
Yes

**Comment by skywalk-explore** [comment]
have you posted the full data anywhere again ? do you have a link ?

**Comment by hacxx-underground** [comment]
> have you posted the full data anywhere again ? do you have a link ?

I only have premium magnet torrent link.

**Comment by skywalk-explore** [comment]
do you mind sharing it with me ? I can pay

**Comment by hacxx-underground** [comment]
> do you mind sharing it with me ? Or where I can buy a premium mgt link

Mail me at hacxx20@gmail.com.
Payment by BTC or Paypal.
Cheaper this way, be sure to have an hd with 200GB + 1.4TB

**Comment by skywalk-explore** [comment]
how much ?

**Comment by hacxx-underground** [comment]
> how much ?

How much can you afford?

**Comment by skywalk-explore** [comment]
20, 30 dollars. I’m still in high school. don’t have a mask budget.

**Comment by hacxx-underground** [comment]
> 20, 30 dollars. I’m still in high school. don’t have a big budget. I can give you the combined dataset I make when I combine the maine voter register with the linkedin data if you’d like ?

30 USD by pp or btc and i send you the link. With NitroFlare links you would spend more as you need to purchase aditional bandwidth. Leave me a email and i will send you the btc wallet or pp email and send you the link.

The email is hacxx20@gmail.com
