### ISSUE TITLE
Shein.com database leaked 1 June 2018 - Free Download - FILE NOT FOUND

### ISSUE THREAD

**Issue by Neffexe** [hacxx-underground/Files#78]
Do you still have this file?

**Comment by hacxx-underground** [comment]
The Shein database is at: DEHASHED - DATABASE - COLLECTION - | - 240+ - DATABASES - | - EMAIL:PASS

**Comment by varun7952** [comment]
Can anyone upload it on mega?

**Comment by hacxx-underground** [comment]
> Can anyone upload it on mega?

No mega link. Nitro link is still up.
