### ISSUE TITLE
Can't download dns DB

### ISSUE THREAD

**Issue by bezgodov** [hacxx-underground/Files#79]
https://github.com/hacxx-underground/Files/blob/main/Dns-shop%20Database%20Leaked%20-%20Free%20Download

**Comment by hacxx-underground** [comment]
> https://github.com/hacxx-underground/Files/blob/main/Dns-shop%20Database%20Leaked%20-%20Free%20Download

The only download link is below.

Download:
https://go.youshort.me/EjYa

If you are unable to get the database, reply back or if you willing to pay leave your email.
