### ISSUE TITLE
Reupload files please

### ISSUE THREAD

**Issue by chujhuj** [hacxx-underground/Files#8]
Reupload files please.
Maybe add new hostings?
https://anonfiles.com
https://mega.nz
https://github.com/hacxx-underground/Files/blob/main/DEHASHED%20-%20DATABASE%20-%20COLLECTION%20-%20%7C%20-%20240%2B%20-%20DATABASES%20-%20%7C%20-%20EMAIL:PASS

**Comment by chujhuj** [comment]
https://github.com/hacxx-underground/Files/blob/main/DEHASHED%20-%20DATABASE%20-%20COLLECTION%20-%20%7C%20-%20240%2B%20-%20DATABASES%20-%20%7C%20-%20EMAIL:PASS

**Comment by hacxx-underground** [comment]
Check here
https://github.com/hacxx-underground/Files/blob/main/%5BREPOST%5D%20DEHASHED%20-%20DATABASE%20-%20COLLECTION%20-%20%7C%20-%20240%2B%20-%20DATABASES%20-%20%7C%20-%20EMAIL:PASS

**Comment by chujhuj** [comment]
Thank You.
Do you have a full MyFitnessPal database?
"In total, there are 143606147 records. The file is 10.47GB uncompressed and 3.63GB compressed"

**Comment by hacxx-underground** [comment]
I don't have the file anymore.

**Comment by hacxx-underground** [comment]
Don't have this file anymore

Check here
https://github.com/hacxx-underground/Files/blob/main/MyFitnessPal%20Full%20Dump%20-%20Free%20Download
