### ISSUE TITLE
Too many files in the main directory

### ISSUE THREAD

**Issue by a-smith-ind** [hacxx-underground/Files#82]
I'm getting this warning.
Sorry, we had to truncate this directory to 1,000 files. 432 entries were omitted from the list.
Could you divide files into more directories, please? So that they can be accessible.

Thanks.

**Comment by hacxx-underground** [comment]
> I'm getting this warning. Sorry, we had to truncate this directory to 1,000 files. 432 entries were omitted from the list. Could you divide files into more directories, please? So that they can be accessible.
> 
> Thanks.

Select a new source.
