### ISSUE TITLE
Could You upload files to anonfiles.com ?

### ISSUE THREAD

**Issue by chujhuj** [hacxx-underground/Files#9]
https://github.com/hacxx-underground/Files/blob/main/%5BREPOST%5D%20DEHASHED%20-%20DATABASE%20-%20COLLECTION%20-%20%7C%20-%20240%2B%20-%20DATABASES%20-%20%7C%20-%20EMAIL:PASS

I would ask you to upload files to the server anonfiles.com. I cant download from nitro: This file is available with Premium only. Reason: this file is larger than 1024mb.
[REPOST] DEHASHED - DATABASE - COLLECTION - | - 240+ - DATABASES - | - EMAIL:PASS

Thank You.

**Comment by hacxx-underground** [comment]
Hi, file to large for anonfiles? Thanks

**Comment by chujhuj** [comment]
Too large for nitroflare.com. 
Anonfiles is ok.

**Comment by hacxx-underground** [comment]
I don't have the file anymore.

No dia sábado, 17 de dezembro de 2022, chujhuj ***@***.***>
escreveu:

**Comment by chujhuj** [comment]
Ok thank you very much.
Regards.
